### ISSUE TITLE
Podification TODO

### ISSUE THREAD

**Issue by bdunne** [ManageIQ/miq_bot#518]
- [ ] Workaround lack of git fetch https://github.com/ManageIQ/miq_bot/pull/516
- [ ] Initial Dockerfile and template https://github.com/ManageIQ/miq_bot/pull/517
- [ ] Migrate NotificationMonitor YAML file contents to a database table or something so that we don't need to carry a PVC for it.  This would also allow us to scale the normal queue worker if desired.
- [ ] Clone a repo on access if it doesn't exist on the filesystem.  This would allow us to drop a couple of PVCs and enable scaling the workers if desired.  Currently the repo needs to be cloned on both worker PVCs.
- [ ] Deploy / upgrade documentation

**Comment by bdunne** [comment]
cc @Fryguy

**Comment by Fryguy** [comment]
Wow I didn't realize we still had that yaml for the notification monitor...I was sure that was already in the db

**Comment by Fryguy** [comment]
For the clone a repo on first access, I had some local code that did that. . I'll see if I can find it

**Comment by bdunne** [comment]
> Wow I didn't realize we still had that yaml for the notification monitor...I was sure that was already in the db

https://github.com/ManageIQ/miq_bot/blob/master/lib/github_notification_monitor.rb#L2

**Comment by Fryguy** [comment]
A few other things off the top of my head

- need UI exposed at bot.manageiq.org
- need instructions on how to sh in so I can add new repos or perhaps add some UI to do it (once UI is exposed)
- need a way to update configuration and force a restart
- we used to use the bot machine for other cron things.  Need a new way to do that.  It could be new bot workers, or perhaps a kube cron job.
- ideally we should move ssh keys into a secret

**Comment by bdunne** [comment]
I updated the description to include most of the things from your list.

For "other cron things", that sounds very specific to our team.  We can probably use the Kubernetes CronJob to handle them, but I don't think they should be part of the bot repo.

SSH keys... yeah, that also needs some testing with the recent rugged ssh work that @NickLaMuro did.  Currently the key and known_hosts file are in a ConfigMap on the cluster.

**Comment by Fryguy** [comment]
@bdunne Since we've already podified this, should we close this one and open issue for the other things left on the list?
